# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
  workingDirectory: 'scores-api'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'scores-api'
    customCommand: 'run build'
  displayName: 'Build'

- task: CopyFiles@2
  displayName: 'Copy web.config to Build folder'
  inputs:
    SourceFolder: 'scores-api'
    Contents: 'web.config'
    TargetFolder: '$(Build.Repository.LocalPath)/scores-api/build'
    OverWrite: true

- task: CopyFiles@2
  displayName: 'Copy Node Modules to Build Folder'
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/scores-api/'
    Contents: 'node_modules'
    TargetFolder: '$(Build.Repository.LocalPath)/scores-api/build'
    OverWrite: true

- task: ArchiveFiles@2
  displayName: 'Zip + Stage Built App'
  inputs:
    rootFolderOrFile: '$(Build.Repository.LocalPath)/scores-api/build'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/scores-api-build$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Stage Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
